### ISSUE TITLE
Mongo based sessions do not allow dots as key names

### ISSUE THREAD

**Issue by avidas** [mattupstate/flask-principal#30]
Hi,

I have been using MongoEngineSessionInterface from flask-mongoengine library for server side sessions in a flask app. The flask principal extension seems to depend on storing identity.id and identity.auth_type in session and retrieving them later to store the identity of user in session. However, in a mongo based session this fails since mongo does not allow dots as key names.

I tried use_sessions=False setting but it was not very clear how to load the identity of the logged in user in that case. 

I could rename them but would rather not create a custom fork of the library. Would you be willing to take in a pull request to change identity.id and identity.auth_type renamed to remove dots?

**Comment by mattupstate** [comment]
Please refer to #40 for an example of how to override how Flask-Principal works with the session.
