### ISSUE TITLE
Is this library maintained?

### ISSUE THREAD

**Issue by Garito** [mattupstate/flask-principal#40]
I've noticed it is not updated since 2014
For instance, my code is affected by this bug: https://github.com/mattupstate/flask-principal/issues/30 but I've checked the code at it is not merged

So the question is the title: is this library maintained? and if not, what alternative did I have?

Thanks!

**Comment by Garito** [comment]
Hi!
Clearly it is not maintained
For those 18 people watching this project: is there a more maintained fork or alternative?

Thanks!

**Comment by jaapz** [comment]
Although the lack of activity might indicate that the library is no longer maintained, you might want to wait a bit longer than 17 hours before giving up on it.

**Comment by Garito** [comment]
It is not a question of waiting 17 hours o 17 days is the fact that the library is not merging important pull request (at least important for me) and has no merge in 2 years

Actually I've stop using @mattupstate one and choose the one with the pull request I'm interested in

I think that if @mattupstate is not answering this messages is because he is not interested in the library any more

Would be more honest to announce this fact but seems to me fair enought if the info or alternative comes to me (which is the case)

Will left this issue open to give @mattupstate time to react but I considere this repo out of date and unmaintained

If someone is interested in using Flask-principal with MongoDB I'm using this fork: https://github.com/Reddine/flask-principal

**Comment by mattupstate** [comment]
@Garito Respectfully, it was a holiday weekend in the USA. There was no chance of me responding to your message until this morning. Additionally, clearly we have different ideas as to what the word "maintained" means. Just because I haven't accepted contributions in quite some time doesn't mean the library isn't usable or stable. For instance, you can __very easily__ get around the baked in usage of sessions if you happen to be using MongoDB for you session store:

```python
principal = Principal(use_sessions=False)

@principal.identity_loader
def my_session_identity_loader():
    if 'identity_id' in session and 'identity_auth_type' in session:
        return Identity(session['identity_id'], session['identity_auth_type'])

@principal.identity_saver
def my_session_identity_saver(identity):
    session['identity_id'] = identity.id
    session['identity_auth_type'] = identity.auth_type
    session.modified = True
```

**Comment by Garito** [comment]
I understand you don't responde quick (as I told before)

The point is that instead to show here the code that solves this issue, you could accept the pull request from the repo I point out before that includes this code

This is a strong sign for me of an avandoned repo (this issue is from august 2014)

But, honestly, I'm not interested in a fight of who is right. I'm here to make timefounder, my app. Flask-Principal seems to be a good library to me, I don't care who maintain it, I would help, no matter what, in everything I could

So I have no problem to use this library or another fork, even, if necessary, fork it by myself (obviously I would prefer not to do so) I only need to know where to go to push forward

If you feel offended, sorry, I wasn't that intent at all

So: what is going to be? This fork, the one I point out, another one you could point?

**Comment by mattupstate** [comment]
I don't believe you need to use a fork as illustrated above.

**Comment by Garito** [comment]
Point me the good way

**Comment by Garito** [comment]
or the reason why this is a bad one...

**Comment by Garito** [comment]
Something?

**Comment by Garito** [comment]
I get it
Thanks!
